package com.typesafe.travel.api.routes

import com.typesafe.travel.advertising.domain.*
import com.typesafe.travel.api.{ExploreSearchPlanner, ExploreSuggestionsPlanner}
import com.typesafe.travel.attraction.api.BookAttractionItemPlanner
import com.typesafe.travel.attraction.domain.{AttractionSuggestionsPlanner, CreateAttractionPlanner, CreateAttractionTicketRulePlanner, CreateAttractionTicketSessionPlanner, CreateAttractionTicketTypePlanner, GetAttractionDetailsPlanner, ListAttractionsPlanner, ListManagedAttractionsPlanner}
import com.typesafe.travel.auth.domain.*
import com.typesafe.travel.content.domain.*
import com.typesafe.travel.flight.api.{BookFlightPlanner, FlightDailyLowestPricesPlanner, FlightSuggestionsPlanner, GetFlightDetailsPlanner, SearchFlightsPlanner}
import com.typesafe.travel.hotel.api.{BookHotelPlanner, GetHotelDetailsPlanner, HotelSuggestionsPlanner, SearchHotelsPlanner}
import com.typesafe.travel.identity.domain.{CreateUserPlanner, GetUserPlanner, LoginUserPlanner, UpdateUserProfilePlanner, UploadUserAvatarPlanner}
import com.typesafe.travel.operations.domain.*
import com.typesafe.travel.order.domain.*
import com.typesafe.travel.tourgroup.domain.*
import com.typesafe.travel.traveler.domain.*
import com.typesafe.travel.train.domain.*

object PlannerDefinitions:
  import PlannerRegistry.RegisteredPlan.WithConnection

  val orderPlanners: PlannerRegistry =
    val registeredPlanners: List[PlannerRegistry.RegisteredPlan] =
      List(
        WithConnection(ListAdvertisementsPlanner),
        WithConnection(CreateAdvertisementPlanner),
        WithConnection(UpdateAdvertisementPlanner),
        WithConnection(SubmitAdvertisementForReviewPlanner),
        WithConnection(PauseAdvertisementPlanner),
        WithConnection(ApproveAdvertisementPlanner),
        WithConnection(RejectAdvertisementPlanner),
        WithConnection(AssignAdvertisementSlotPlanner),
        WithConnection(UploadAdvertisementImagePlanner),
        WithConnection(GenerateAdvertisementImageCandidatesPlanner),
        WithConnection(GenerateAdvertisementTextCandidatesPlanner),
        WithConnection(FlightSuggestionsPlanner),
        WithConnection(SearchFlightsPlanner),
        WithConnection(FlightDailyLowestPricesPlanner),
        WithConnection(GetFlightDetailsPlanner),
        WithConnection(BookFlightPlanner),
        WithConnection(HotelSuggestionsPlanner),
        WithConnection(SearchHotelsPlanner),
        WithConnection(GetHotelDetailsPlanner),
        WithConnection(BookHotelPlanner),
        WithConnection(BookAttractionItemPlanner),
        WithConnection(AttractionSuggestionsPlanner),
        WithConnection(ListAttractionsPlanner),
        WithConnection(GetAttractionDetailsPlanner),
        WithConnection(ListManagedAttractionsPlanner),
        WithConnection(CreateAttractionPlanner),
        WithConnection(CreateAttractionTicketTypePlanner),
        WithConnection(CreateAttractionTicketSessionPlanner),
        WithConnection(CreateAttractionTicketRulePlanner),
        WithConnection(SignupPlanner),
        WithConnection(LoginPlanner),
        WithConnection(CurrentUserPlanner),
        WithConnection(LogoutPlanner),
        WithConnection(LogoutOtherSessionsPlanner),
        WithConnection(ListAuthSessionsPlanner),
        WithConnection(ChangePasswordPlanner),
        WithConnection(BlogSuggestionsPlanner),
        WithConnection(ListBlogPostsPlanner),
        WithConnection(GetBlogPostPlanner),
        WithConnection(CreateBlogPostPlanner),
        WithConnection(UpdateBlogPostPlanner),
        WithConnection(SaveBlogDraftPlanner),
        WithConnection(PublishBlogPostPlanner),
        WithConnection(ApproveBlogPostPlanner),
        WithConnection(RejectBlogPostPlanner),
        WithConnection(ArchiveBlogPostPlanner),
        WithConnection(AddBlogCommentPlanner),
        WithConnection(DeleteBlogCommentPlanner),
        WithConnection(LikeBlogPostPlanner),
        WithConnection(UnlikeBlogPostPlanner),
        WithConnection(LikeBlogCommentPlanner),
        WithConnection(UnlikeBlogCommentPlanner),
        WithConnection(FavoriteBlogPostPlanner),
        WithConnection(UnfavoriteBlogPostPlanner),
        WithConnection(FollowBlogUserPlanner),
        WithConnection(BlockBlogUserPlanner),
        WithConnection(ListBlogNotificationsPlanner),
        WithConnection(GetBlogProfilePlanner),
        WithConnection(UpdateBlogProfilePrivacyPlanner),
        WithConnection(ListBlogFollowersPlanner),
        WithConnection(ListBlogFollowingPlanner),
        WithConnection(ListMyReviewsPlanner),
        WithConnection(ListReviewsByResourcePlanner),
        WithConnection(GetReviewSummaryPlanner),
        WithConnection(CheckReviewEligibilityPlanner),
        WithConnection(CreateReviewPlanner),
        WithConnection(UpdateReviewPlanner),
        WithConnection(DeleteReviewPlanner),
        WithConnection(UploadReviewImagePlanner),
        WithConnection(ListFeedbackThreadsPlanner),
        WithConnection(EnsureReviewFeedbackThreadPlanner),
        WithConnection(EnsureOrderCancellationThreadPlanner),
        WithConnection(SendFeedbackMessagePlanner),
        WithConnection(CreateOrderCancellationMessagePlanner),
        WithConnection(HandleOrderCancellationRequestPlanner),
        WithConnection(MarkFeedbackThreadReadPlanner),
        WithConnection(EscalateFeedbackThreadPlanner),
        WithConnection(ExploreSuggestionsPlanner),
        WithConnection(ExploreSearchPlanner),
        WithConnection(CreateUserPlanner),
        WithConnection(LoginUserPlanner),
        WithConnection(GetUserPlanner),
        WithConnection(UploadUserAvatarPlanner),
        WithConnection(UpdateUserProfilePlanner),
        WithConnection(ManagerLoginPlanner),
        WithConnection(CurrentManagerPlanner),
        WithConnection(ManagerLogoutPlanner),
        WithConnection(ManagerLogoutOtherSessionsPlanner),
        WithConnection(ListManagerSessionsPlanner),
        WithConnection(ChangeManagerPasswordPlanner),
        WithConnection(RegisterAirlineManagerPlanner),
        WithConnection(RegisterHotelManagerPlanner),
        WithConnection(RegisterAttractionManagerPlanner),
        WithConnection(RegisterSiteAdminPlanner),
        WithConnection(ListManagerTasksPlanner),
        WithConnection(BatchConfirmManagerTasksPlanner),
        WithConnection(BatchRejectManagerTasksPlanner),
        WithConnection(ListManagerFlightsPlanner),
        WithConnection(ListManagerFlightOrdersPlanner),
        WithConnection(ListManagerHotelsPlanner),
        WithConnection(ListManagerRefundTasksPlanner),
        WithConnection(UpdateAirlineManagerProfilePlanner),
        WithConnection(UpdateHotelManagerProfilePlanner),
        WithConnection(CreateManagerFlightPlanner),
        WithConnection(ToggleManagerFlightStatusPlanner),
        WithConnection(CreateManagerRoomTypePlanner),
        WithConnection(ConfirmManagerBookingItemPlanner),
        WithConnection(RejectManagerBookingItemPlanner),
        WithConnection(ApproveManagerRefundPlanner),
        WithConnection(RejectManagerRefundPlanner),
        WithConnection(ListOrdersPlanner),
        WithConnection(CreateOrderPlanner),
        WithConnection(GetOrderPlanner),
        WithConnection(CreatePaymentLinkPlanner),
        WithConnection(SubmitOrderPlanner),
        WithConnection(PayOrderPlanner),
        WithConnection(CancelOrderPlanner),
        WithConnection(RequestRefundPlanner),
        WithConnection(ApproveRefundPlanner),
        WithConnection(SettleRefundPlanner),
        WithConnection(FindOrderPaymentPlanner),
        WithConnection(CreateTravelerPlanner),
        WithConnection(UpdateTravelerPlanner),
        WithConnection(ListTravelersPlanner),
        WithConnection(DeleteTravelerPlanner),
        WithConnection(TrainSuggestionsPlanner),
        WithConnection(RegisterRailwayManagerPlanner),
        WithConnection(ListManagedTrainsPlanner),
        WithConnection(CreateTrainJourneyPlanner),
        WithConnection(SearchTrainsPlanner),
        WithConnection(GetTrainDetailsPlanner),
        WithConnection(BookTrainItemPlanner),
        WithConnection(CreateTourGroupPlanner),
        WithConnection(ListTourGroupsPlanner),
        WithConnection(GetTourGroupDetailsPlanner),
        WithConnection(JoinTourGroupPlanner),
        WithConnection(LeaveTourGroupPlanner),
        WithConnection(AddMembershipTravelerPlanner),
        WithConnection(RemoveMembershipTravelerPlanner),
        WithConnection(KickTourGroupMemberPlanner),
        WithConnection(BlacklistTourGroupMemberPlanner),
        WithConnection(TransferTourGroupLeaderPlanner),
        WithConnection(CreateTourGroupPlanItemPlanner),
        WithConnection(CreateTourGroupPlanOptionPlanner),
        WithConnection(CreateTourGroupSelectionPlanner),
        WithConnection(SubmitTourGroupSelectionPlanner)
      )

    PlannerRegistry(
      registeredPlanners.map(planner => planner.name -> planner).toMap
    )
