import { approveAdvertisement } from '@/microservices/advertising/api/ApproveAdvertisementPlanner'
import { assignAdvertisementSlot } from '@/microservices/advertising/api/AssignAdvertisementSlotPlanner'
import { getAdvertisementDeliverySettings, saveAdvertisementDeliverySettings } from '@/microservices/advertising/api/AdvertisementDeliverySettingsPlanners'
import { createAdvertisement } from '@/microservices/advertising/api/CreateAdvertisementPlanner'
import { generateAdvertisementImageCandidates } from '@/microservices/advertising/api/GenerateAdvertisementImageCandidatesPlanner'
import { generateAdvertisementTextCandidates } from '@/microservices/advertising/api/GenerateAdvertisementTextCandidatesPlanner'
import { listMyAdvertisements, listPendingAdvertisements, listReviewedAdvertisements, listDeliverableAdvertisements } from '@/microservices/advertising/api/ListAdvertisementsPlanner'
import { pauseAdvertisement } from '@/microservices/advertising/api/PauseAdvertisementPlanner'
import { pauseAdvertisementDisplay } from '@/microservices/advertising/api/PauseAdvertisementDisplayPlanner'
import { rejectAdvertisement } from '@/microservices/advertising/api/RejectAdvertisementPlanner'
import { submitAdvertisementForReview } from '@/microservices/advertising/api/SubmitAdvertisementForReviewPlanner'
import { updateAdvertisement } from '@/microservices/advertising/api/UpdateAdvertisementPlanner'
import { uploadAdvertisementImage } from '@/microservices/advertising/api/UploadAdvertisementImagePlanner'
import { listAttractions, getAttraction, uploadAttractionImage } from '@/microservices/attraction/api/AttractionPlanners'
import { getHealth, signupUser, loginUserWithPassword, logoutUser, getCurrentUserSession, changeUserPassword, listUserSessions, logoutCurrentUserSession, logoutOtherUserSessions } from '@/microservices/auth/api/AuthPlanners'
import { loginManagerAuth, logoutManagerAuth, getCurrentManagerSession, changeManagerPassword, listManagerSessions, logoutCurrentManagerSession, logoutOtherManagerSessions } from '@/microservices/auth/api/ManagerAuthPlanners'
import { listBlogPosts, listShortBlogPosts, listBlogSuggestions, uploadBlogImage, getBlogPost, listBlogModerationPosts, approveBlogPost, rejectBlogPost, saveBlogDraft, publishBlogPost, createBlogPost, updateBlogPost, archiveBlogPost, addBlogComment, deleteBlogComment, likeBlogPost, unlikeBlogPost, likeBlogComment, unlikeBlogComment, favoriteBlogPost, unfavoriteBlogPost, followBlogUser, blockBlogUser, listBlogNotifications, getBlogProfile, updateBlogProfilePrivacy, listBlogFollowers, listBlogFollowing } from '@/microservices/content/api/BlogPlanners'
import { listExploreSuggestions, searchExplore } from '@/microservices/content/api/ExplorePlanners'
import { ensureOrderCancellationThread, listMyFeedbackThreads, listManagerFeedbackThreads, listSiteAdminFeedbackThreads, sendFeedbackMessage, createOrderCancellationMessage, handleOrderCancellationRequest, markFeedbackThreadRead, escalateFeedbackThread } from '@/microservices/content/api/FeedbackPlanners'
import { listMyReviews, listReviewsByResource, getReviewResourceSummary, getReviewEligibility, createReview, updateReview, uploadReviewImage, deleteReview } from '@/microservices/content/api/ReviewPlanners'
import { searchFlightsPlanner, flightDailyLowestPricesPlanner, getFlightDetailsPlanner, bookFlightPlanner } from '@/microservices/flight/api'
import { searchHotelsPlanner, getHotelDetailsPlanner, uploadHotelRoomTypeImage } from '@/microservices/hotel/api'
import { createUser, loginUser, getUser, uploadUserAvatar, updateUserProfile } from '@/microservices/identity/api/UserQueryPlanners'
import { registerAirlineManager, registerHotelManager, registerSiteAdmin, updateSiteAdminManagerProfile, registerRailwayManager, registerAttractionManager, listManagedAttractions, createAttraction, createAttractionTicketType, createAttractionTicketSession, createAttractionTicketRule, listManagedTrains, createTrainJourney, createManagerRoomType, listManagedHotels, listManagerTasks, batchConfirmManagerBookingItems, batchRejectManagerBookingItems, listManagerFlights, listManagerFlightOrders, listManagerRefundTasks, updateAirlineManagerProfile, updateHotelManagerProfile, createManagerFlight, toggleManagerFlightStatus, confirmManagerBookingItem, rejectManagerBookingItem } from '@/microservices/operations/api/ManagerPlanners'
import { createPaymentLink } from '@/microservices/order/api/FindOrderPaymentPlanner'
import { createOrder, addTrainItemToOrder, addAttractionItemToOrder, createHotelOrder, getOrder, listOrders, payOrder, cancelOrder, requestRefund, approveRefund, rejectRefund } from '@/microservices/order/api/OrderPlanners'
import { createTourGroup, uploadTourGroupCoverImage, listTourGroups, getTourGroup, joinTourGroup, leaveTourGroup, addTourGroupMembershipTraveler, removeTourGroupMembershipTraveler, kickTourGroupMember, blacklistTourGroupMember, transferTourGroupLeader, createTourGroupPlanItem, createTourGroupPlanOption, createTourGroupSelection, submitTourGroupSelection, confirmTourGroupSelection, rejectTourGroupSelection, payTourGroupSelection, batchPayTourGroupSelections, batchConfirmTourGroupSelections, batchRejectTourGroupSelections, listTourGroupBookings, getTourGroupChatSettings, updateTourGroupChatSettings, listTourGroupChatMessages, sendTourGroupChatMessage, listTourGroupDirectConversations, listTourGroupConversations, searchTourGroupConversations, searchTourGroupMessages, getOrCreateTourGroupDirectConversation, listDirectConversationMessages, listConversationMessages, markConversationRead, uploadConversationAttachment, sendConversationMessage, sendDirectConversationMessage, editConversationMessage, deleteConversationMessage, recallConversationMessage, addConversationReaction, removeConversationReaction, updateDirectConversationMuteState, updateDirectConversationArchiveState } from '@/microservices/tour-group/api/TourGroupPlanners'
import { listTrains, getTrain } from '@/microservices/train/api/TrainPlanners'
import { createTraveler, updateTraveler, listTravelers, deleteTraveler } from '@/microservices/traveler/api/TravelerPlanners'

export const travelMvpApiClient = {
  approveAdvertisement,
  assignAdvertisementSlot,
  getAdvertisementDeliverySettings,
  saveAdvertisementDeliverySettings,
  createAdvertisement,
  generateAdvertisementImageCandidates,
  generateAdvertisementTextCandidates,
  listMyAdvertisements,
  listPendingAdvertisements,
  listReviewedAdvertisements,
  listDeliverableAdvertisements,
  pauseAdvertisement,
  pauseAdvertisementDisplay,
  rejectAdvertisement,
  submitAdvertisementForReview,
  updateAdvertisement,
  uploadAdvertisementImage,
  listAttractions,
  getAttraction,
  uploadAttractionImage,
  getHealth,
  signupUser,
  loginUserWithPassword,
  logoutUser,
  getCurrentUserSession,
  changeUserPassword,
  listUserSessions,
  logoutCurrentUserSession,
  logoutOtherUserSessions,
  loginManagerAuth,
  logoutManagerAuth,
  getCurrentManagerSession,
  changeManagerPassword,
  listManagerSessions,
  logoutCurrentManagerSession,
  logoutOtherManagerSessions,
  listBlogPosts,
  listShortBlogPosts,
  listBlogSuggestions,
  uploadBlogImage,
  getBlogPost,
  listBlogModerationPosts,
  approveBlogPost,
  rejectBlogPost,
  saveBlogDraft,
  publishBlogPost,
  createBlogPost,
  updateBlogPost,
  archiveBlogPost,
  addBlogComment,
  deleteBlogComment,
  likeBlogPost,
  unlikeBlogPost,
  likeBlogComment,
  unlikeBlogComment,
  favoriteBlogPost,
  unfavoriteBlogPost,
  followBlogUser,
  blockBlogUser,
  listBlogNotifications,
  getBlogProfile,
  updateBlogProfilePrivacy,
  listBlogFollowers,
  listBlogFollowing,
  listExploreSuggestions,
  searchExplore,
  ensureOrderCancellationThread,
  listMyFeedbackThreads,
  listManagerFeedbackThreads,
  listSiteAdminFeedbackThreads,
  sendFeedbackMessage,
  createOrderCancellationMessage,
  handleOrderCancellationRequest,
  markFeedbackThreadRead,
  escalateFeedbackThread,
  listMyReviews,
  listReviewsByResource,
  getReviewResourceSummary,
  getReviewEligibility,
  createReview,
  updateReview,
  uploadReviewImage,
  deleteReview,
  searchFlightsPlanner,
  flightDailyLowestPricesPlanner,
  getFlightDetailsPlanner,
  bookFlightPlanner,
  searchHotelsPlanner,
  getHotelDetailsPlanner,
  uploadHotelRoomTypeImage,
  createUser,
  loginUser,
  getUser,
  uploadUserAvatar,
  updateUserProfile,
  registerAirlineManager,
  registerHotelManager,
  registerSiteAdmin,
  updateSiteAdminManagerProfile,
  registerRailwayManager,
  registerAttractionManager,
  listManagedAttractions,
  createAttraction,
  createAttractionTicketType,
  createAttractionTicketSession,
  createAttractionTicketRule,
  listManagedTrains,
  createTrainJourney,
  createManagerRoomType,
  listManagedHotels,
  listManagerTasks,
  batchConfirmManagerBookingItems,
  batchRejectManagerBookingItems,
  listManagerFlights,
  listManagerFlightOrders,
  listManagerRefundTasks,
  updateAirlineManagerProfile,
  updateHotelManagerProfile,
  createManagerFlight,
  toggleManagerFlightStatus,
  confirmManagerBookingItem,
  rejectManagerBookingItem,
  createPaymentLink,
  createOrder,
  addTrainItemToOrder,
  addAttractionItemToOrder,
  createHotelOrder,
  getOrder,
  listOrders,
  payOrder,
  cancelOrder,
  requestRefund,
  approveRefund,
  rejectRefund,
  createTourGroup,
  uploadTourGroupCoverImage,
  listTourGroups,
  getTourGroup,
  joinTourGroup,
  leaveTourGroup,
  addTourGroupMembershipTraveler,
  removeTourGroupMembershipTraveler,
  kickTourGroupMember,
  blacklistTourGroupMember,
  transferTourGroupLeader,
  createTourGroupPlanItem,
  createTourGroupPlanOption,
  createTourGroupSelection,
  submitTourGroupSelection,
  confirmTourGroupSelection,
  rejectTourGroupSelection,
  payTourGroupSelection,
  batchPayTourGroupSelections,
  batchConfirmTourGroupSelections,
  batchRejectTourGroupSelections,
  listTourGroupBookings,
  getTourGroupChatSettings,
  updateTourGroupChatSettings,
  listTourGroupChatMessages,
  sendTourGroupChatMessage,
  listTourGroupDirectConversations,
  listTourGroupConversations,
  searchTourGroupConversations,
  searchTourGroupMessages,
  getOrCreateTourGroupDirectConversation,
  listDirectConversationMessages,
  listConversationMessages,
  markConversationRead,
  uploadConversationAttachment,
  sendConversationMessage,
  sendDirectConversationMessage,
  editConversationMessage,
  deleteConversationMessage,
  recallConversationMessage,
  addConversationReaction,
  removeConversationReaction,
  updateDirectConversationMuteState,
  updateDirectConversationArchiveState,
  listTrains,
  getTrain,
  createTraveler,
  updateTraveler,
  listTravelers,
  deleteTraveler,
}
