import { approveAdvertisement } from '@/microservices/advertising/api/ApproveAdvertisementPlanner'
import { assignAdvertisementSlot } from '@/microservices/advertising/api/AssignAdvertisementSlotPlanner'
import { createAdvertisement } from '@/microservices/advertising/api/CreateAdvertisementPlanner'
import { listMyAdvertisements, listPendingAdvertisements, listReviewedAdvertisements, listDeliverableAdvertisements } from '@/microservices/advertising/api/ListAdvertisementsPlanner'
import { pauseAdvertisement } from '@/microservices/advertising/api/PauseAdvertisementPlanner'
import { rejectAdvertisement } from '@/microservices/advertising/api/RejectAdvertisementPlanner'
import { submitAdvertisementForReview } from '@/microservices/advertising/api/SubmitAdvertisementForReviewPlanner'
import { updateAdvertisement } from '@/microservices/advertising/api/UpdateAdvertisementPlanner'
import { uploadAdvertisementImage } from '@/microservices/advertising/api/UploadAdvertisementImagePlanner'
import { listAttractions, getAttraction } from '@/microservices/attraction/api/AttractionPlanners'
import { getHealth, signupUser, loginUserWithPassword, logoutUser, getCurrentUserSession, changeUserPassword, listUserSessions, logoutCurrentUserSession, logoutOtherUserSessions } from '@/microservices/auth/api/AuthPlanners'
import { loginManagerAuth, logoutManagerAuth, getCurrentManagerSession, changeManagerPassword, listManagerSessions, logoutCurrentManagerSession, logoutOtherManagerSessions } from '@/microservices/auth/api/ManagerAuthPlanners'
import { listBlogPosts, listBlogSuggestions, uploadBlogImage, getBlogPost, listBlogModerationPosts, approveBlogPost, rejectBlogPost, createBlogPost, updateBlogPost, archiveBlogPost, addBlogComment, deleteBlogComment, likeBlogPost, unlikeBlogPost } from '@/microservices/content/api/BlogPlanners'
import { listExploreSuggestions, searchExplore } from '@/microservices/content/api/ExplorePlanners'
import { createReviewFeedbackThread, listMyFeedbackThreads, listManagerFeedbackThreads, listSiteAdminFeedbackThreads, sendFeedbackMessage, markFeedbackThreadRead, escalateFeedbackThread } from '@/microservices/content/api/FeedbackPlanners'
import { listMyReviews, listReviewsByResource, getReviewResourceSummary, getReviewEligibility, createReview, updateReview, uploadReviewImage, deleteReview } from '@/microservices/content/api/ReviewPlanners'
import { listFlights, getFlight, createFlightOrder } from '@/microservices/flight/api/FlightQueryPlanners'
import { listHotels, getHotel } from '@/microservices/hotel/api/HotelQueryPlanners'
import { createUser, loginUser, getUser, uploadUserAvatar } from '@/microservices/identity/api/UserQueryPlanners'
import { loginManager, registerAirlineManager, registerHotelManager, registerSiteAdmin, registerRailwayManager, loginRailwayManager, registerAttractionManager, loginAttractionManager, listManagedAttractions, createAttraction, createAttractionTicketType, createAttractionTicketSession, createAttractionTicketRule, listManagedTrains, createTrainJourney, createManagerRoomType, listManagedHotels, listManagerTasks, batchConfirmManagerBookingItems, batchRejectManagerBookingItems, listManagerFlights, listManagerRefundTasks, createManagerFlight, confirmManagerBookingItem, rejectManagerBookingItem } from '@/microservices/operations/api/ManagerPlanners'
import { createPaymentLink } from '@/microservices/order/api/FindOrderPaymentPlanner'
import { createOrder, addTrainItemToOrder, addAttractionItemToOrder, createHotelOrder, getOrder, listOrders, payOrder, cancelOrder, requestRefund, approveRefund, rejectRefund } from '@/microservices/order/api/OrderPlanners'
import { createTourGroup, listTourGroups, getTourGroup, joinTourGroup, addTourGroupMembershipTraveler, createTourGroupPlanItem, createTourGroupPlanOption, createTourGroupSelection, submitTourGroupSelection, confirmTourGroupSelection, rejectTourGroupSelection, payTourGroupSelection, batchPayTourGroupSelections, batchConfirmTourGroupSelections, batchRejectTourGroupSelections, listTourGroupBookings, getTourGroupChatSettings, updateTourGroupChatSettings, listTourGroupChatMessages, sendTourGroupChatMessage, listTourGroupDirectConversations, listTourGroupConversations, searchTourGroupConversations, searchTourGroupMessages, getOrCreateTourGroupDirectConversation, listDirectConversationMessages, listConversationMessages, markConversationRead, uploadConversationAttachment, sendConversationMessage, sendDirectConversationMessage, editConversationMessage, deleteConversationMessage, recallConversationMessage, addConversationReaction, removeConversationReaction, updateDirectConversationMuteState, updateDirectConversationArchiveState } from '@/microservices/tour-group/api/TourGroupPlanners'
import { listTrains, getTrain } from '@/microservices/train/api/TrainPlanners'
import { createTraveler, updateTraveler, listTravelers, deleteTraveler } from '@/microservices/traveler/api/TravelerPlanners'

export const travelMvpApiClient = {
  approveAdvertisement,
  assignAdvertisementSlot,
  createAdvertisement,
  listMyAdvertisements,
  listPendingAdvertisements,
  listReviewedAdvertisements,
  listDeliverableAdvertisements,
  pauseAdvertisement,
  rejectAdvertisement,
  submitAdvertisementForReview,
  updateAdvertisement,
  uploadAdvertisementImage,
  listAttractions,
  getAttraction,
  getHealth,
  signupUser,
  loginUserWithPassword,
  logoutUser,
  getCurrentUserSession,
  changeUserPassword,
  listUserSessions,
  logoutCurrentUserSession,
  logoutOtherUserSessions,
  loginManagerAuth,
  logoutManagerAuth,
  getCurrentManagerSession,
  changeManagerPassword,
  listManagerSessions,
  logoutCurrentManagerSession,
  logoutOtherManagerSessions,
  listBlogPosts,
  listBlogSuggestions,
  uploadBlogImage,
  getBlogPost,
  listBlogModerationPosts,
  approveBlogPost,
  rejectBlogPost,
  createBlogPost,
  updateBlogPost,
  archiveBlogPost,
  addBlogComment,
  deleteBlogComment,
  likeBlogPost,
  unlikeBlogPost,
  listExploreSuggestions,
  searchExplore,
  createReviewFeedbackThread,
  listMyFeedbackThreads,
  listManagerFeedbackThreads,
  listSiteAdminFeedbackThreads,
  sendFeedbackMessage,
  markFeedbackThreadRead,
  escalateFeedbackThread,
  listMyReviews,
  listReviewsByResource,
  getReviewResourceSummary,
  getReviewEligibility,
  createReview,
  updateReview,
  uploadReviewImage,
  deleteReview,
  listFlights,
  getFlight,
  createFlightOrder,
  listHotels,
  getHotel,
  createUser,
  loginUser,
  getUser,
  uploadUserAvatar,
  loginManager,
  registerAirlineManager,
  registerHotelManager,
  registerSiteAdmin,
  registerRailwayManager,
  loginRailwayManager,
  registerAttractionManager,
  loginAttractionManager,
  listManagedAttractions,
  createAttraction,
  createAttractionTicketType,
  createAttractionTicketSession,
  createAttractionTicketRule,
  listManagedTrains,
  createTrainJourney,
  createManagerRoomType,
  listManagedHotels,
  listManagerTasks,
  batchConfirmManagerBookingItems,
  batchRejectManagerBookingItems,
  listManagerFlights,
  listManagerRefundTasks,
  createManagerFlight,
  confirmManagerBookingItem,
  rejectManagerBookingItem,
  createPaymentLink,
  createOrder,
  addTrainItemToOrder,
  addAttractionItemToOrder,
  createHotelOrder,
  getOrder,
  listOrders,
  payOrder,
  cancelOrder,
  requestRefund,
  approveRefund,
  rejectRefund,
  createTourGroup,
  listTourGroups,
  getTourGroup,
  joinTourGroup,
  addTourGroupMembershipTraveler,
  createTourGroupPlanItem,
  createTourGroupPlanOption,
  createTourGroupSelection,
  submitTourGroupSelection,
  confirmTourGroupSelection,
  rejectTourGroupSelection,
  payTourGroupSelection,
  batchPayTourGroupSelections,
  batchConfirmTourGroupSelections,
  batchRejectTourGroupSelections,
  listTourGroupBookings,
  getTourGroupChatSettings,
  updateTourGroupChatSettings,
  listTourGroupChatMessages,
  sendTourGroupChatMessage,
  listTourGroupDirectConversations,
  listTourGroupConversations,
  searchTourGroupConversations,
  searchTourGroupMessages,
  getOrCreateTourGroupDirectConversation,
  listDirectConversationMessages,
  listConversationMessages,
  markConversationRead,
  uploadConversationAttachment,
  sendConversationMessage,
  sendDirectConversationMessage,
  editConversationMessage,
  deleteConversationMessage,
  recallConversationMessage,
  addConversationReaction,
  removeConversationReaction,
  updateDirectConversationMuteState,
  updateDirectConversationArchiveState,
  listTrains,
  getTrain,
  createTraveler,
  updateTraveler,
  listTravelers,
  deleteTraveler,
}
