package com.typesafe.travel.tourgroup.domain

// Compatibility aliases kept temporarily while the new single-purpose DTO files are adopted across the codebase.
type UploadTourGroupCoverImagePlannerResponse = UploadTourGroupCoverImageResponse
type TourGroupByIdPlannerRequest = GetTourGroupDetailsPlannerRequest
type TourGroupSummaryPlannerResponse = TourGroupSummaryResponse
type TourGroupMembershipPlannerResponse = TourGroupMembershipResponse
type TourGroupMembershipTravelerPlannerResponse = TourGroupMembershipTravelerResponse
type TourGroupBlacklistPlannerResponse = TourGroupBlacklistResponse
type TourGroupDetailsPlannerResponse = TourGroupDetailsResponse
type TourGroupListPlannerResponse = TourGroupListResponse
