package com.typesafe.travel.tourgroup.domain

// Compatibility aliases kept temporarily while the new single-purpose DTO files are adopted across the codebase.
type TourGroupChatSettingsPlannerResponse = TourGroupChatSettingsResponse
type TourGroupConversationSummaryPlannerResponse = TourGroupConversationSummaryResponse
type TourGroupConversationListPlannerResponse = TourGroupConversationListResponse
type TourGroupMessageAttachmentPlannerResponse = TourGroupMessageAttachmentResponse
type TourGroupMessageReactionPlannerResponse = TourGroupMessageReactionResponse
type TourGroupMessagePlannerResponse = TourGroupMessageResponse
type TourGroupMessageListPlannerResponse = TourGroupMessageListResponse
type TourGroupMessageSearchPlannerResponse = TourGroupMessageSearchResponse
type TourGroupMessageSearchResultPlannerResponse = TourGroupMessageSearchResultResponse
