// 本文件集中导出 auth 域的前端类型：既包含与后端 planner 同名的主定义，也保留旧页面兼容类型。

export type { LoginPlannerRequest } from '@/microservices/auth/objects/LoginPlannerRequest'
export type { CurrentUserPlannerResponse } from '@/microservices/auth/objects/CurrentUserPlannerResponse'
export type { SessionPlannerRequest } from '@/microservices/auth/objects/SessionPlannerRequest'
export type { UserSessionPlannerResponse } from '@/microservices/auth/objects/UserSessionPlannerResponse'
export type { UserSessionListPlannerResponse } from '@/microservices/auth/objects/UserSessionListPlannerResponse'
export type { ManagerLoginPlannerRequest } from '@/microservices/auth/objects/ManagerLoginPlannerRequest'
export type { CurrentManagerPlannerResponse } from '@/microservices/auth/objects/CurrentManagerPlannerResponse'
export type { ManagerSessionPlannerRequest } from '@/microservices/auth/objects/ManagerSessionPlannerRequest'
export type { ManagerSessionListPlannerResponse } from '@/microservices/auth/objects/ManagerSessionListPlannerResponse'
export type { SignupPlannerRequest } from '@/microservices/auth/objects/SignupPlannerRequest'
export type { LogoutOtherSessionsPlannerRequest } from '@/microservices/auth/objects/LogoutOtherSessionsPlannerRequest'
export type { ChangePasswordPlannerRequest } from '@/microservices/auth/objects/ChangePasswordPlannerRequest'
export type { AuthStatusPlannerResponse } from '@/microservices/auth/objects/AuthStatusPlannerResponse'
export type { ManagerChangePasswordPlannerRequest } from '@/microservices/auth/objects/ManagerChangePasswordPlannerRequest'
export type { ManagerAuthStatusPlannerResponse } from '@/microservices/auth/objects/ManagerAuthStatusPlannerResponse'

export type { CurrentUserSessionResponse } from '@/microservices/auth/objects/CurrentUserSessionResponse'
export type { CurrentManagerSessionResponse } from '@/microservices/auth/objects/CurrentManagerSessionResponse'
export type { UserSessionResponse } from '@/microservices/auth/objects/UserSessionResponse'
export type { UserSessionListResponse } from '@/microservices/auth/objects/UserSessionListResponse'
export type { ManagerSessionResponse } from '@/microservices/auth/objects/ManagerSessionResponse'
export type { ManagerType } from '@/microservices/auth/objects/ManagerType'
export type { AttractionAdminSessionResponse } from '@/microservices/auth/objects/AttractionAdminSessionResponse'
export type { TrainAdminSessionResponse } from '@/microservices/auth/objects/TrainAdminSessionResponse'
export type { UserResponse } from '@/microservices/auth/objects/UserResponse'
