// 本文件定义管理端前端传输类型，覆盖后台任务和审批接口。

export type { ManagerBatchDecisionResponse } from '@/microservices/operations/objects/ManagerBatchDecisionResponse'
export type { ManagerRefundTaskListResponse } from '@/microservices/operations/objects/ManagerRefundTaskListResponse'
export type { ManagerRefundTaskResponse } from '@/microservices/operations/objects/ManagerRefundTaskResponse'
export type { ManagerTaskListResponse } from '@/microservices/operations/objects/ManagerTaskListResponse'
export type { ManagerTaskResponse } from '@/microservices/operations/objects/ManagerTaskResponse'
export type { ManagerFlightOrderListResponse } from '@/microservices/operations/objects/ManagerFlightOrderListResponse'
export type { ManagerFlightOrderResponse } from '@/microservices/operations/objects/ManagerFlightOrderResponse'
export type { ManagerFlightOrderTravelerResponse } from '@/microservices/operations/objects/ManagerFlightOrderTravelerResponse'
export type { CreateManagerRoomTypePlannerRequest } from '@/microservices/operations/hotel/objects/CreateManagerRoomTypePlannerRequest'
export type { ManagerHotelListPlannerResponse } from '@/microservices/operations/hotel/objects/ManagerHotelListPlannerResponse'
export type { ManagerHotelPlannerResponse } from '@/microservices/operations/hotel/objects/ManagerHotelPlannerResponse'
export type { ManagerHotelRoomTypePlannerResponse } from '@/microservices/operations/hotel/objects/ManagerHotelRoomTypePlannerResponse'
export type { ManagerScopedPlannerRequest } from '@/microservices/operations/hotel/objects/ManagerScopedPlannerRequest'
export type { RegisterHotelManagerPlannerRequest } from '@/microservices/operations/hotel/objects/RegisterHotelManagerPlannerRequest'
export type { UpdateHotelManagerProfilePlannerRequest } from '@/microservices/operations/hotel/objects/UpdateHotelManagerProfilePlannerRequest'
