// 本文件定义资源服务前端传输类型，供图片和媒体字段复用。

export type { AttractionListResponse } from '@/microservices/attraction/objects/AttractionListResponse'
export type { AttractionResponse } from '@/microservices/attraction/objects/AttractionResponse'
export type { AttractionSearchQuery } from '@/microservices/attraction/objects/AttractionSearchQuery'
export type { AttractionTicketSessionResponse } from '@/microservices/attraction/objects/AttractionTicketSessionResponse'
export type { AttractionTicketTypeResponse } from '@/microservices/attraction/objects/AttractionTicketTypeResponse'
export type { AttractionTicketTypeRuleResponse } from '@/microservices/attraction/objects/AttractionTicketTypeRuleResponse'
export type { BookAttractionItemRequest } from '@/microservices/attraction/objects/BookAttractionItemRequest'
export type { BookHotelPlannerRequest } from '@/microservices/hotel/objects/BookHotelPlannerRequest'
export type { BookTrainItemRequest } from '@/microservices/train/objects/BookTrainItemRequest'
export type { HotelListPlannerResponse } from '@/microservices/hotel/objects/HotelListPlannerResponse'
export type { HotelPlannerResponse } from '@/microservices/hotel/objects/HotelPlannerResponse'
export type { HotelSearchPlannerRequest } from '@/microservices/hotel/objects/HotelSearchPlannerRequest'
export type { RoomTypeSummaryResponse } from '@/microservices/hotel/objects/RoomTypeSummaryResponse'
export type { TrainListResponse } from '@/microservices/train/objects/TrainListResponse'
export type { TrainRefundPolicyResponse } from '@/microservices/train/objects/TrainRefundPolicyResponse'
export type { TrainResponse } from '@/microservices/train/objects/TrainResponse'
export type { TrainSearchQuery } from '@/microservices/train/objects/TrainSearchQuery'
export type { TrainSeatAssignmentResponse } from '@/microservices/train/objects/TrainSeatAssignmentResponse'
export type { TrainSeatInventoryResponse } from '@/microservices/train/objects/TrainSeatInventoryResponse'
export type { TrainSeatResponse } from '@/microservices/train/objects/TrainSeatResponse'
export type { TrainSegmentPriceResponse } from '@/microservices/train/objects/TrainSegmentPriceResponse'
