package com.typesafe.travel.shared.kernel

final case class UserId(value: String) extends AnyVal
final case class CredentialId(value: String) extends AnyVal
final case class SessionId(value: String) extends AnyVal
final case class TravelerId(value: String) extends AnyVal
final case class AirlineId(value: String) extends AnyVal
final case class FlightId(value: String) extends AnyVal
final case class CabinInventoryId(value: String) extends AnyVal
final case class HotelId(value: String) extends AnyVal
final case class RoomTypeId(value: String) extends AnyVal
final case class RoomInventoryId(value: String) extends AnyVal
final case class TrainId(value: String) extends AnyVal
final case class TrainStopId(value: String) extends AnyVal
final case class TrainSeatInventoryId(value: String) extends AnyVal
final case class TrainSeatId(value: String) extends AnyVal
final case class TrainSeatAllocationId(value: String) extends AnyVal
final case class TrainSegmentPriceId(value: String) extends AnyVal
final case class TrainRefundPolicySegmentId(value: String) extends AnyVal
final case class AttractionId(value: String) extends AnyVal
final case class TicketTypeId(value: String) extends AnyVal
final case class TicketEligibilityRuleId(value: String) extends AnyVal
final case class AttractionTicketSessionId(value: String) extends AnyVal
final case class ReservationId(value: String) extends AnyVal
final case class ManagerId(value: String) extends AnyVal
final case class OrderId(value: String) extends AnyVal
final case class OrderItemId(value: String) extends AnyVal
final case class PaymentId(value: String) extends AnyVal
final case class RefundId(value: String) extends AnyVal
final case class ReviewId(value: String) extends AnyVal
final case class BlogId(value: String) extends AnyVal
final case class BlogCommentId(value: String) extends AnyVal
final case class BlogLikeId(value: String) extends AnyVal
final case class BlogImageId(value: String) extends AnyVal
final case class ReviewImageId(value: String) extends AnyVal
final case class TourGroupId(value: String) extends AnyVal
final case class TourGroupMembershipId(value: String) extends AnyVal
final case class TourGroupMembershipTravelerId(value: String) extends AnyVal
final case class GroupPlanItemId(value: String) extends AnyVal
final case class GroupPlanOptionId(value: String) extends AnyVal
final case class GroupPlanSelectionId(value: String) extends AnyVal
final case class GroupPlanSelectionTravelerId(value: String) extends AnyVal
final case class GroupSelectionOrderLinkId(value: String) extends AnyVal
final case class TourGroupConversationId(value: String) extends AnyVal
final case class TourGroupConversationParticipantId(value: String) extends AnyVal
final case class TourGroupMessageId(value: String) extends AnyVal
final case class TourGroupMessageAttachmentId(value: String) extends AnyVal
final case class TourGroupMessageReactionId(value: String) extends AnyVal
final case class StaffId(value: String) extends AnyVal
final case class AuditTaskId(value: String) extends AnyVal
final case class SupportTicketId(value: String) extends AnyVal
