package com.typesafe.travel.tourgroup.domain

import com.typesafe.travel.shared.kernel.*

import java.time.LocalDate

enum TourGroupError(val message: String) extends DomainError:
  case GroupCapacityWasInvalid(capacity: Int)
      extends TourGroupError(s"Tour group capacity '$capacity' must be greater than zero")
  case GroupDateRangeWasInvalid(startDate: LocalDate, endDate: LocalDate)
      extends TourGroupError(s"Tour group start date '$startDate' must be before end date '$endDate'")
  case GroupWasNotFound(groupId: TourGroupId)
      extends TourGroupError(s"Tour group '${groupId.value}' was not found")
  case MembershipWasNotFound(membershipId: TourGroupMembershipId)
      extends TourGroupError(s"Tour group membership '${membershipId.value}' was not found")
  case ActiveMembershipAlreadyExists(groupId: TourGroupId, userId: UserId)
      extends TourGroupError(s"User '${userId.value}' already has an active membership in group '${groupId.value}'")
  case PlanItemWasNotFound(planItemId: GroupPlanItemId)
      extends TourGroupError(s"Group plan item '${planItemId.value}' was not found")
  case PlanOptionWasNotFound(optionId: GroupPlanOptionId)
      extends TourGroupError(s"Group plan option '${optionId.value}' was not found")
  case SelectionWasNotFound(selectionId: GroupPlanSelectionId)
      extends TourGroupError(s"Group selection '${selectionId.value}' was not found")
  case OrganizerScopeDidNotMatch(groupId: TourGroupId, actingUserId: UserId)
      extends TourGroupError(s"User '${actingUserId.value}' is not organizer of group '${groupId.value}'")
  case MembershipScopeDidNotMatch(membershipId: TourGroupMembershipId, actingUserId: UserId)
      extends TourGroupError(s"User '${actingUserId.value}' does not own membership '${membershipId.value}'")
  case MembershipTravelerDidNotBelongToUser(travelerId: TravelerId, actingUserId: UserId)
      extends TourGroupError(s"Traveler '${travelerId.value}' does not belong to user '${actingUserId.value}'")
  case MembershipTravelerAlreadyExists(membershipId: TourGroupMembershipId, travelerId: TravelerId)
      extends TourGroupError(s"Traveler '${travelerId.value}' is already part of membership '${membershipId.value}'")
  case GroupCapacityWasExceeded(groupId: TourGroupId, capacity: Int, requestedUsedCapacity: Int)
      extends TourGroupError(s"Tour group '${groupId.value}' capacity $capacity would be exceeded by used capacity $requestedUsedCapacity")
  case GroupWasNotOpen(groupId: TourGroupId, status: TourGroupStatus)
      extends TourGroupError(s"Tour group '${groupId.value}' is not open in status $status")
  case PlanOptionDidNotBelongToPlanItem(optionId: GroupPlanOptionId, planItemId: GroupPlanItemId)
      extends TourGroupError(s"Plan option '${optionId.value}' does not belong to plan item '${planItemId.value}'")
  case PlanOptionResourceTypeDidNotMatchPlanItem(planItemId: GroupPlanItemId, itemType: GroupPlanItemType, resourceType: GroupPlanOptionResourceType)
      extends TourGroupError(s"Plan item '${planItemId.value}' of type $itemType cannot use resource type $resourceType")
  case SelectionTravelerWasEmpty(planItemId: GroupPlanItemId)
      extends TourGroupError(s"Plan item '${planItemId.value}' requires at least one traveler")
  case SelectionTravelerWasNotInMembership(selectionId: GroupPlanSelectionId, travelerId: TravelerId)
      extends TourGroupError(s"Traveler '${travelerId.value}' is not part of selection '${selectionId.value}' membership")
  case SelectionQuantityWasInvalid(quantity: Int)
      extends TourGroupError(s"Selection quantity '$quantity' must be greater than zero")
  case SelectionWasNotSubmittable(selectionId: GroupPlanSelectionId, status: GroupPlanSelectionStatus)
      extends TourGroupError(s"Selection '${selectionId.value}' cannot be submitted from status $status")
  case SelectionWasNotConfirmable(selectionId: GroupPlanSelectionId, status: GroupPlanSelectionStatus)
      extends TourGroupError(s"Selection '${selectionId.value}' cannot be confirmed from status $status")
  case SelectionWasNotRejectable(selectionId: GroupPlanSelectionId, status: GroupPlanSelectionStatus)
      extends TourGroupError(s"Selection '${selectionId.value}' cannot be rejected from status $status")
  case SelectionWasNotPayable(selectionId: GroupPlanSelectionId, status: GroupPlanSelectionStatus)
      extends TourGroupError(s"Selection '${selectionId.value}' cannot be paid from status $status")
  case SelectionReviewNoteWasEmpty(selectionId: GroupPlanSelectionId)
      extends TourGroupError(s"Selection '${selectionId.value}' reject review note must not be empty")
  case SelectionQuantityDidNotMatchTravelerCount(selectionId: GroupPlanSelectionId, quantity: Int, travelerCount: Int)
      extends TourGroupError(s"Selection '${selectionId.value}' quantity $quantity must match traveler count $travelerCount")
  case PlanItemSequenceWasInvalid(sequenceNo: Int)
      extends TourGroupError(s"Group plan item sequence '$sequenceNo' must be greater than zero")
  case PlanItemTimeWindowWasInvalid(planItemId: GroupPlanItemId)
      extends TourGroupError(s"Plan item '${planItemId.value}' has an invalid time window")
  case SelectionWasAlreadyLinked(selectionId: GroupPlanSelectionId, orderId: OrderId)
      extends TourGroupError(s"Selection '${selectionId.value}' is already linked to order '${orderId.value}'")
  case RequiredFieldWasEmpty(fieldName: String)
      extends TourGroupError(s"Field '$fieldName' must not be empty")
  case ConversationWasNotFound(conversationId: TourGroupConversationId)
      extends TourGroupError(s"Conversation '${conversationId.value}' was not found")
  case GroupMemberWasNotFound(groupId: TourGroupId, userId: UserId)
      extends TourGroupError(s"User '${userId.value}' is not an active member of group '${groupId.value}'")
  case DirectConversationWasNotAllowed(groupId: TourGroupId, actingUserId: UserId, targetUserId: UserId)
      extends TourGroupError(s"User '${actingUserId.value}' cannot start a direct conversation with '${targetUserId.value}' in group '${groupId.value}'")
  case ConversationAccessWasDenied(conversationId: TourGroupConversationId, actingUserId: UserId)
      extends TourGroupError(s"User '${actingUserId.value}' cannot access conversation '${conversationId.value}'")
  case MessageContentWasEmpty()
      extends TourGroupError("Message content must not be empty")
  case DirectConversationTargetWasInvalid(userId: UserId)
      extends TourGroupError(s"User '${userId.value}' cannot start a direct conversation with themselves")
  case ConversationWasClosed(conversationId: TourGroupConversationId)
      extends TourGroupError(s"Conversation '${conversationId.value}' is closed")
  case MessageWasNotFound(messageId: TourGroupMessageId)
      extends TourGroupError(s"Message '${messageId.value}' was not found")
  case MessageAccessWasDenied(messageId: TourGroupMessageId, actingUserId: UserId)
      extends TourGroupError(s"User '${actingUserId.value}' cannot modify message '${messageId.value}'")
  case MessageEditWasNotAllowed(messageId: TourGroupMessageId, status: TourGroupMessageStatus)
      extends TourGroupError(s"Message '${messageId.value}' cannot be edited from status $status")
  case MessageDeleteWasNotAllowed(messageId: TourGroupMessageId, status: TourGroupMessageStatus)
      extends TourGroupError(s"Message '${messageId.value}' cannot be deleted from status $status")
  case MessageRecallWasNotAllowed(messageId: TourGroupMessageId, status: TourGroupMessageStatus)
      extends TourGroupError(s"Message '${messageId.value}' cannot be recalled from status $status")
  case MessageReactionTypeWasInvalid(reactionType: String)
      extends TourGroupError(s"Reaction '$reactionType' is not supported")
  case MessageAttachmentWasNotFound(attachmentId: TourGroupMessageAttachmentId)
      extends TourGroupError(s"Attachment '${attachmentId.value}' was not found")
  case MessageAttachmentUploadWasNotAllowed(reason: String)
      extends TourGroupError(s"Message attachment upload was not allowed: $reason")

